# Generated by Django 5.2.8 on 2025-12-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_type', '0001_initial'),
        ('nutritional_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_type.foodtype')),
                ('nutritional_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritional_plan.nutritionalplan')),
            ],
        ),
    ]
