# Generated by Django 5.2.8 on 2025-11-23 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('model_meal_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmealtype',
            name='food',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='food.food'),
            preserve_default=False,
        ),
    ]
