# Generated by Django 5.2.8 on 2025-11-23 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_meal_type', '0002_modelmealtype_food'),
        ('nutritional_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmealtype',
            name='nutritional_plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nutritional_plan.nutritionalplan'),
            preserve_default=False,
        ),
    ]
