# Generated by Django 5.2.8 on 2025-12-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_type', '0001_initial'),
        ('meal_type_nutritional_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMealTypeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('meal_calorie_budget', models.FloatField(blank=True, editable=False, null=True)),
                ('food_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_type.foodtype')),
                ('meal_type_nutritional_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_type_nutritional_plan.mealtypenutritionalplan')),
            ],
        ),
    ]
