# Generated by Django 5.2.8 on 2025-12-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('allows_snack', models.BooleanField(default=False)),
                ('contains_rich_in_carb', models.BooleanField()),
                ('contains_rich_in_prot', models.BooleanField()),
                ('contains_rich_in_fat', models.BooleanField()),
                ('contains_rich_in_fiber', models.BooleanField()),
                ('is_dessert', models.BooleanField(default=False)),
            ],
        ),
    ]
