# Generated by Django 5.2.8 on 2025-11-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allows_snack', models.BooleanField()),
                ('contains_prot_source', models.BooleanField()),
                ('contains_carb_source', models.BooleanField()),
                ('contains_fat_source', models.BooleanField()),
                ('contains_fiber_source', models.BooleanField()),
            ],
        ),
    ]
