# Generated by Django 5.2.8 on 2025-11-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='is_dessert',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
