# Generated by Django 5.2.8 on 2025-12-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_type', '0001_initial'),
        ('meal_type_nutritional_plan', '0001_initial'),
        ('nutritional_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='nutritional_plan',
            field=models.ManyToManyField(through='meal_type_nutritional_plan.MealTypeNutritionalPlan', to='nutritional_plan.nutritionalplan'),
        ),
    ]
