# Generated by Django 5.2.8 on 2025-12-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('kcal', models.FloatField(blank=True, editable=False, null=True)),
                ('total_carbs', models.FloatField(blank=True, editable=False, null=True)),
                ('protein', models.FloatField(blank=True, editable=False, null=True)),
                ('total_fat', models.FloatField(blank=True, editable=False, null=True)),
                ('food_name', models.CharField(blank=True, editable=False, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_type.foodtype')),
            ],
        ),
    ]
