# Generated by Django 5.2.8 on 2025-12-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logged_meal', '0001_initial'),
        ('meal_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmeal',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_type.mealtype'),
        ),
    ]
