# Generated by Django 5.2.8 on 2025-12-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logged_meal', '0002_initial'),
        ('model_meal_type_component', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmeal',
            name='model_meal_type_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_meal_type_component.modelmealtypecomponent'),
        ),
    ]
