# Generated by Django 5.2.8 on 2025-11-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('portion_size', models.IntegerField()),
                ('measure_unit', models.CharField(choices=[('g', 'gram'), ('mL', 'mililiter')])),
                ('snack', models.BooleanField()),
                ('calories', models.IntegerField()),
                ('total_carbs', models.FloatField()),
                ('proteins', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('container_total_weight', models.IntegerField()),
                ('saturated_fat', models.FloatField(blank=True, null=True)),
                ('polyunsaturated_fat', models.FloatField(blank=True, null=True)),
                ('monounsaturated_fat', models.FloatField(blank=True, null=True)),
                ('trans_fat', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('sugar', models.FloatField(blank=True, null=True)),
                ('added_sugar', models.FloatField(blank=True, null=True)),
                ('vitamin_a', models.FloatField(blank=True, null=True)),
                ('vitamin_c', models.FloatField(blank=True, null=True)),
                ('vitamin_d', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
