# Generated by Django 5.2.8 on 2025-12-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='container_total_weight',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
