# Generated by Django 5.2.8 on 2025-11-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='proteins',
            new_name='protein',
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='measure_unit',
            field=models.CharField(choices=[('g', 'gram'), ('mL', 'milliliter')]),
        ),
    ]
