# Generated by Django 5.2.8 on 2025-12-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0002_alter_foodtype_container_total_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='fiber',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='kcal',
            field=models.FloatField(),
        ),
    ]
