# Generated by Django 5.2.8 on 2025-11-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0002_rename_proteins_foodtype_protein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='protein_per_un',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='rich_in',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='total_carbs_per_un',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='total_fat_per_un',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
