# Generated by Django 5.2.8 on 2025-12-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0003_alter_foodtype_fiber_alter_foodtype_kcal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
