# Generated by Django 5.2.8 on 2025-11-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0003_foodtype_protein_per_un_foodtype_rich_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='total_calories_per_un',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
