# Generated by Django 5.2.8 on 2025-11-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0004_foodtype_total_calories_per_un'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='total_calories_per_un',
            new_name='calories_per_un',
        ),
    ]
