# Generated by Django 5.2.8 on 2025-12-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0004_alter_foodtype_fiber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='container_total_weight',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
