# Generated by Django 5.2.8 on 2025-12-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0005_alter_foodtype_container_total_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='container_total_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
