# Generated by Django 5.2.8 on 2025-11-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0005_rename_total_calories_per_un_foodtype_calories_per_un'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='added_sugar',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='monounsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='polyunsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='saturated_fat',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='trans_fat',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='vitamin_a',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='vitamin_c',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='vitamin_d',
        ),
    ]
