# Generated by Django 5.2.8 on 2025-11-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0006_remove_foodtype_added_sugar_remove_foodtype_calcium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='container_total_weight',
        ),
    ]
