# Generated by Django 5.2.8 on 2025-11-30 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0007_remove_foodtype_container_total_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='snack',
        ),
    ]
