# Generated by Django 5.2.8 on 2025-11-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0008_remove_foodtype_snack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='calories',
            new_name='kcal',
        ),
        migrations.RenameField(
            model_name='foodtype',
            old_name='calories_per_un',
            new_name='kcal_per_un',
        ),
    ]
