# Generated by Django 5.2.8 on 2025-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0009_rename_calories_foodtype_kcal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='added_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='container_total_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='iron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='monounsaturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='polyunsaturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='snack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='trans_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='vitamin_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='vitamin_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='vitamin_d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
