# Generated by Django 5.2.8 on 2025-11-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_type', '0010_foodtype_added_sugar_foodtype_calcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
