# Generated by Django 5.2.8 on 2025-11-23 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_type', '0002_mealtype_is_dessert'),
        ('nutritional_goal', '0002_nutritionalgoal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalPlan',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('nutritional_goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nutritional_goal.nutritionalgoal')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_type.mealtype')),
            ],
        ),
    ]
