# Generated by Django 5.2.8 on 2025-12-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_type', '0001_initial'),
        ('meal_type_nutritional_plan', '0001_initial'),
        ('nutritional_goal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalPlan',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('nutritional_goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nutritional_goal.nutritionalgoal')),
                ('meal_type', models.ManyToManyField(through='meal_type_nutritional_plan.MealTypeNutritionalPlan', to='meal_type.mealtype')),
            ],
        ),
    ]
