# Generated by Django 5.2.8 on 2025-12-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_preference', '0001_initial'),
        ('food_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('biological_sex', models.CharField(choices=[('F', 'female'), ('M', 'male')])),
                ('physical_activity_level', models.FloatField(choices=[(1.2, 'sedentário (pouco ou nenhum exercício)'), (1.375, 'pouco ativo (exercício/esporte leve 1-3x/semana)'), (1.55, 'moderadamente ativo (exercício/esporte moderado 3-5x/semana)'), (1.725, 'muito ativo (exercício/esporte pesado 6-7x/semana)'), (1.9, 'extremamente ativo (exercício/esporte pesado e trabalho físico intenso diariamente ou treino de 2x/dia)')])),
                ('basal_metabolic_rate', models.FloatField(blank=True, editable=False, null=True)),
                ('food_type', models.ManyToManyField(through='food_preference.FoodPreference', to='food_type.foodtype')),
            ],
        ),
    ]
