# Generated by Django 5.2.8 on 2025-12-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_preference', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodpreference',
            old_name='food',
            new_name='food_type',
        ),
    ]
