# Generated by Django 5.2.8 on 2025-12-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTypeNutritionalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_type.mealtype')),
            ],
        ),
    ]
