# Generated by Django 5.2.8 on 2025-12-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_type_nutritional_plan', '0001_initial'),
        ('nutritional_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtypenutritionalplan',
            name='nutritional_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritional_plan.nutritionalplan'),
        ),
    ]
