# Generated by Django 5.2.8 on 2025-11-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_budget', models.IntegerField()),
                ('protein_percentage', models.FloatField()),
                ('carbs_percentage', models.FloatField()),
                ('fat_percentage', models.FloatField()),
                ('weight_goal', models.FloatField()),
                ('goal', models.CharField(choices=[(-1, 'lose'), (0, 'maintain'), (1, 'gain')])),
            ],
        ),
    ]
