# Generated by Django 5.2.8 on 2025-12-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_budget', models.IntegerField()),
                ('protein_percentage', models.FloatField()),
                ('carbs_percentage', models.FloatField()),
                ('fat_percentage', models.FloatField()),
                ('weight_goal', models.FloatField()),
                ('goal', models.CharField(choices=[('lose', 'lose'), ('maintain', 'maintain'), ('gain', 'gain')])),
                ('progress_speed', models.IntegerField(default=0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
