# Generated by Django 5.2.8 on 2025-11-23 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_goal', '0001_initial'),
        ('user', '0002_remove_user_nutritional_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalgoal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
