# Generated by Django 5.2.8 on 2025-11-22 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_type', '0001_initial'),
        ('nutritional_goal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('loves', 'loves'), ('hates', 'hates')])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_type.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('biological_sex', models.CharField(choices=[('F', 'female'), ('M', 'male')])),
                ('physical_activity_level', models.CharField(choices=[(1, 'sedentário'), (2, 'atividade leve'), (3, 'atividade moderada'), (4, 'atividade intensa')])),
                ('food_preferences', models.ManyToManyField(through='user.FoodPreference', to='food_type.foodtype')),
                ('nutritional_goal', models.ManyToManyField(to='nutritional_goal.nutritionalgoal')),
            ],
        ),
        migrations.AddField(
            model_name='foodpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
