# Generated by Django 5.2.8 on 2025-11-22 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_type.foodtype')),
            ],
        ),
    ]
