# Generated by Django 5.2.8 on 2025-11-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
