# Generated by Django 5.2.8 on 2025-11-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_food_description_food_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='total_carbs',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='total_fat',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
