# Generated by Django 5.2.8 on 2025-11-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_calories_food_food_name_food_protein_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='calories',
            new_name='kcal',
        ),
    ]
